name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build-Quasar-Frontend'
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: listdir
        run: 'ls'
      - name: Build-Quasar
        uses: ./gh-action-build-quasar # Uses an action in the root directory
        id: build-quasar
        with:
          sourcelocation: /github/workspace/qna
      - name: Upload SPA files as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: spa
          # Directory containing files to upload
          path: ./qna/dist/spa
