name: CI

on:
  push:
    branches: 
      - dev

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build-Quasar-Frontend'
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: List-Dir
        run: 'ls'
      - name: Build-Quasar
        uses: ./gh-action-build-quasar # Uses an action in the root directory
        id: build-quasar
        with:
          sourcelocation: /github/workspace/qna
      - name: Upload SPA files as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: spa
          # Directory containing files to upload
          path: ./qna/dist/spa
  build-functions:
    runs-on: [windows-latest]
    name: 'Build-Fn-Backend'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-And-Package-Functions
        shell: pwsh
        run: cd .\deployment ; .\package-functionapp-to-zip.ps1
      - name: Upload Functions package as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: functions
          # Directory containing files to upload
          path: ./deployment/functionpackage/qna-fn-backend.zip
  deploy-arm-templates:
    needs: [build-frontend, build-functions]
    runs-on: ubuntu-latest
    name: Deploy-Arm-Templates
    steps:
      - name: Login-To-Azure
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
