name: CI

on:
  push:
    branches: 
      - dev

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build-Quasar-Frontend'
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: List-Dir
        run: 'ls'
      - name: Build-Quasar
        uses: ./gh-action-build-quasar # Uses an action in the root directory
        id: build-quasar
        with:
          sourcelocation: /github/workspace/qna
      - name: Upload SPA files as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: spa
          # Directory containing files to upload
          path: ./qna/dist/spa
  build-functions:
    runs-on: [windows-latest]
    name: 'Build-Fn-Backend'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build-And-Package-Functions
        shell: pwsh
        run: cd .\deployment ; .\package-functionapp-to-zip.ps1
      - name: Upload Functions package as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: functions
          # Directory containing files to upload
          path: ./deployment/functionpackage/qna-fn-backend.zip
  deploy-arm-templates:
    needs: [build-frontend, build-functions]
    runs-on: ubuntu-latest
    container:
      image: azuresdk/azure-powershell-core # => run step in container, as documented here: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
      #volumes: 
      #  - /home/runner/work/qnademo/qnademo:/github/workspace
    name: Deploy-Arm-Templates
    steps:
      # - name: CLI-Login-To-Azure
      #  uses: Azure/login@v1
      #  with:
      #    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: PWSH-Login-To-Azure
        shell: pwsh
        run: |
          # Login to Azure:
          Add-Type -Path "/usr/local/share/powershell/Modules/Az.Profile/PreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.dll" ;
          Import-Module Az.Profile -Force ;
          $Password = ConvertTo-SecureString ${{ secrets.SP_PROD_DEPL_PWD }} -AsPlainText -Force ;
          $Creds = New-Object System.Management.Automation.PSCredential( '${{ secrets.SP_PROD_DEPL_APPID }}', $Password) ;
          Connect-AzAccount -ServicePrincipal -SubscriptionId '33761810-ec30-441e-ad3e-50f029e977f7' -TenantId '72f988bf-86f1-41af-91ab-2d7cd011db47' -Credential $Creds ;
          # Change active subscription:
          # $context = Get-AzSubscription -SubscriptionId '33761810-ec30-441e-ad3e-50f029e977f7'
          # Set-AzContext $context
      - name: Deploy-ARM-Template
        shell: pwsh
        run: |
          echo $(ls) ;
          echo $(ls /__w) ;
          cd /__w/qnademo ;
          echo 'switched to __w/qndemo' ;
          echo $(ls) ;
          cd /__w/qnademo/qnademo ;
          echo 'switched to __w/qndemo/qnademo' ;
          echo $(ls) ;
          cd /__w/qnademo/qnademo/deployment ;
          ls ;
          ./deploy-infra -NameRGForNestedTemplates 'qna-qa-infra' -LocationRGForNestedTemplates westeurope  -NameStorageAcctForNestedTemplates qnaqastornestedtempl -ResourceGroupPrefix qna-qa -ArtifactPrefix qnaqa -AADClientId 'd03fc97e-cc4e-4758-944a-43fe4cf3eecc' -AADB2CIssuer 'https://xstofb2c.b2clogin.com/xstofb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_susi' ;
          
          
